project:
  type: book

book:
  title: "Libro_PROBABILITY_Jamy"
  author: "Norah Jones"
  date: "8/7/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

