---
title: "contenido"
---

1 Introduction 1 1.1 Equally Likely Outcomes 2 1.2 Interpretations 11 1.3 Distributions 19 1.4 Conditional Probability and Independence . 33 1.5 Bayes' Rule . . . . . 47 1.6 Sequences of Events 56 Summary ..... 73 Review Exercises . 75 2 Repeated Trials and Sampling 79 2.1 The Binomial Distribution . 80 2.2 Normal Approximation: Method 93 2.3 Normal Approximation: Derivation (Optional) . 111 2.4 Poisson Approximation ............. 117

2.5 Random Sampling Summary ..... Review Exercises . 3 Random Variables 3.1 Introduction 3.2 Expectation. 3.3 Standard Deviation and Normal Approximation 3.4 Discrete Distributions .. 3.5 The Poisson Distribution. 3.6 Symmetry (Optional) . Summary ..... Review Exercises . 4 Continuous Distributions 4.1 Probability Densities . . 4.2 Exponential and Gamma Distributions 4.3 Hazard Rates (Optional) 4.4 Change of Variable . . . 4.5 Cumulative Distribution Functions 4.6 Order Statistics (Optional) . Summary ..... Review Exercises . 5 Continuous Joint Distributions 5.1 Uniform Distributions 5.2 Densities \...\... . 5.3 Independent Normal Variables 5.4 Operations (Optional) Summary ..... Review Exercises . 123 130 132 139 139 162 185 208 222 237 248 250 259 260 278 296 302 311 325 334 336 339 340 346 357 371 386 387

6 Dependence 6.1 Conditional Distributions: Discrete Case 6.2 Conditional Expectation: Discrete Case. 6.3 Conditioning: Density Case 6.4 Covariance and Correlation 6.5 Bivariate Normal Summary ..... Review Exercises . Distribution Summaries Discrete .. Continuous Beta \... Binomial Exponential . Gamma \... Geometric and Negative Binomial Hypergeometric Normal Poisson Uniform. Examinations Solutions to Examinations Appendices 1 2 3 4 5 Counting Sums .. Calculus. Exponents and Logarithms Normal Table ....... . Brief Solutions to Odd-Numbered Exercises Index Contents . XI 393 393 401 410 430 449 464 466 475 476 477 478 479 480 481 482 483 484 486 487 489 498 505 507 515 517 525 531 533
