---
title: "Introduction2"
---

This chapter introduces the basic ,::oncepts of probability theory. These are the notions of: an outcome space, or set of all possible outcomes of some kind; events represented mathematically as subsets of an outcome space; and probability as a function of these events or subsets.

-   The probability of an event is a measure of the likelihood or chance that the event occurs, on a scale from 0 to 1.

-   Section 1.1 introduces these ideas in the simplest setting of equally likely outcomes.

-   Section 1.2 treats two important interpretations of probability: approximation of long-run frequencies and subjective judgment of uncertainty.

-   This rule is huilt in to the idea of a probability distribution, introduced in Section 1.3.

### 1.1 Equally Likely Outcomes

-   Probability is an extension of the idea of a proportion, or ratio of a part to a whole.

It would then be said that the probability of choosing a woman is 70%; the odds in favor of choosing a woman are 7 to 3 (or 7/3 to 1); and the odds against choosing a woman are 3 to 7 (or 3/7 to 1).

Equally Likely Outcomes If all outcomes in a finite set f2 are equally likely, the probability of A is the number of outcomes in A divided by the total number of outcomes: P(A) = #(A) #(f2)

Picking a number between 1 and 100. Suppose there is a box of 100 tickets marked 1,2,3, \... , 100. A ticket is drawn at random from the box. Here are some events, with their descriptions as subsets and their probabilities obtained by counting. All possible numbers are assumed equally likely.

Rolling two dice. A fair die is rolled and the number on the top face is noted. Then another fair die is rolled, and the number on its top face is noted.

What is the probability that the sum of the two numbers showing is 5?

What is the probability that one of the dice shows 2, and the other shows 4?

What is the probability that the second number rolled is greater than the first number?

What is the probability that the second number rolled is less than the first number rolled?

Rolling two n-sided dice. Repeat the above example for two rolls of a die with n faces numbered 1,2, \... , n, assuming n 2: 4. Find the chance that the sum is 5.

Find the chance that one roll is a 2, the other is a 4.

Find the chance that the second number is greater than the first.

Find the chance that the first number is bigger.

### Odds

### Exercises 1. 1

## 1.2 Interpretations
