REGRESSION ANALYSIS: SOME ADDITIONAL TECHNIQUES

\

# **CHAPTER OVERVIEW** 

En este capítulo se analizan algunas herramientas y conceptos adicionales que resultan útiles en el análisis de regresión. La presentación incluye ampliaciones de las ideas y técnicas básicas del análisis de regresión que se presentaron en los capítulos 9 y 10.

**TOPICS**

\

11.1 INTRODUCTION

11.2 QUALITATIVE INDEPENDENT VARIABLES

11.3 VARIABLE SELECTION PROCEDURES

11.4 LOGISTIC REGRESSION

11.5 SUMMARY

\

**LEARNING OUTCOMES**

After studying this chapter, the student will

1.  comprender cómo incluir variables cualitativas en un análisis de regresión.

2.  comprender cómo utilizar procedimientos de selección automatizada de variables para desarrollar modelos de regresión.

3.  er capaz de realizar regresión logística para variables dependientes dicotómicas y politómicas.

    \

### **11.1 INTRODUCTION**

Los conceptos básicos y la metodología del análisis de regresión se cubren en los Capítulos 9 y 10. En el Capítulo 9 analizamos la situación en la que el objetivo es obtener una ecuación que se pueda utilizar para hacer predicciones y estimaciones sobre alguna variable dependiente a partir del conocimiento de alguna otra variable única que llamamos variable independiente, predictora o explicativa. En el Capítulo 10, las ideas y técnicas aprendidas en el Capítulo 9 se amplían para cubrir la situación en la que se cree que la inclusión de información sobre dos o más variables independientes producirá una mejor ecuación para usar en la realización de predicciones y estimaciones. El análisis de regresión es una herramienta estadística compleja y poderosa que se utiliza ampliamente en la investigación de las ciencias de la salud. Hacer justicia al tema requiere más espacio del que está disponible en un libro de texto introductorio de estadística. Sin embargo, para beneficio de aquellos que desean una cobertura adicional del análisis de regresión, presentamos en este capítulo algunos temas adicionales que deberían resultar útiles para el estudiante y el profesional de la estadística.\

**Supuestos de regresión revisados** ​​Como aprendimos en los capítulos 9 y 10, existen varios supuestos que sustentan el uso adecuado de los procedimientos de regresión. A menudo, hay ciertas mediciones que influyen fuertemente en la forma de una distribución o impactan la magnitud de la varianza de una variable medida. Otras veces, ciertas variables independientes que se utilizan para desarrollar un modelo están altamente correlacionadas, lo que lleva al desarrollo de un modelo que puede no ser único o correcto.

**Datos no normales** Muchas veces los datos que se utilizan para construir un modelo de regresión no se distribuyen normalmente. Uno puede desear explorar la posibilidad de que algunos de los puntos de datos observados sean valores atípicos o que afecten desproporcionadamente la distribución de los datos. Tal investigación puede llevarse a cabo de manera informal construyendo un diagrama de dispersión y buscando observaciones que no parezcan encajar con las demás. Alternativamente, muchos paquetes de computadora producen pruebas formales para evaluar posibles observaciones atípicas en la variable dependiente o en las variables independientes. Sin embargo, siempre depende del investigador justificar qué observaciones se eliminarán del conjunto de datos antes del análisis.

\
A menudo, se puede intentar una transformación de los datos. Las transformaciones matemáticas son útiles porque no afectan las relaciones subyacentes entre las variables. Dado que las pruebas de hipótesis para los coeficientes de regresión se basan en estadísticas de distribución normal, las transformaciones de datos a veces pueden normalizar los datos en la medida necesaria para realizar dichas pruebas. Las transformaciones simples, como tomar la raíz cuadrada de las mediciones o tomar el logaritmo de las mediciones, son bastante comunes.

**EXAMPLE 11.1.1**

Los investigadores se interesaron por las concentraciones sanguíneas de delta-9-tetrahidrocannabinol ()-9-THC), el componente psicotrópico activo de la marihuana, de 25 sujetos de investigación. Estos datos se presentan en la Tabla 11.1.1, al igual que estos mismos datos después de utilizar una transformación log10.

En la Figura 11.1.1 se muestran los diagramas de caja y bigotes del software SPSS para estos datos. Los datos brutos están claramente sesgados y se identifica un valor atípico (observación 25). Una transformación log10, que suele ser útil para estos datos sesgados, elimina la magnitud del valor atípico y da como resultado una distribución que es mucho más simétrica respecto de la mediana. Por lo tanto, los datos transformados podrían utilizarse en lugar de los datos brutos para construir el modelo de regresión. Aunque los datos simétricos no implican necesariamente que sean normales, sí dan como resultado un modelo más apropiado. Las pruebas formales de normalidad, como se mencionó anteriormente, siempre deben realizarse antes del análisis.

\
**Varianzas de error desiguales** Cuando las varianzas de los términos de error no son iguales, podemos obtener una ecuación satisfactoria para el modelo, pero, debido a que se viola el supuesto de que las varianzas de error son iguales, no podremos realizar pruebas de hipótesis adecuadas sobre los coeficientes del modelo. Tal como sucedió al superar el problema de no normalidad, las transformaciones de las variables de regresión pueden reducir el impacto de las varianzas de error desiguales.

**Variables independientes correlacionadas** La multicolinealidad es un problema común que surge cuando se intenta construir un modelo utilizando muchas variables independientes. La multicolinealidad ocurre cuando hay un alto grado de correlación entre las variables independientes. Por ejemplo, imaginemos que queremos encontrar una ecuación que relacione la altura y el peso con la presión arterial. Una variable común que se deriva de la altura y el peso se llama índice de masa corporal (IMC). Si intentamos encontrar una ecuación que relacione la altura, el peso y el IMC con la presión arterial, podemos esperar encontrarnos con problemas analíticos porque el IMC, por definición, está altamente correlacionado tanto con la altura como con el peso.

El problema surge matemáticamente cuando se derivan las soluciones para los coeficientes de regresión. Como los datos están correlacionados, es posible que no se encuentren soluciones que sean exclusivas de un modelo determinado. La solución menos compleja para la multicolinealidad es calcular las correlaciones entre todas las variables independientes y conservar solo aquellas variables que no están altamente correlacionadas. Una regla práctica conservadora para eliminar la redundancia en el conjunto de datos es eliminar las variables que están relacionadas con otras con un coeficiente de correlación significativo superior a 0,7.

\
**EXAMPLE 11.1.2**

En un estudio sobre la obesidad y el síndrome metabólico se utilizaron datos recopilados de 15 estudiantes, entre los que se incluían la presión arterial sistólica (PAS), el peso y el IMC. Estos datos se presentan en la Tabla 11.1.2.

Las correlaciones entre las tres variables se muestran en la Figura 11.1.2. La correlación muy grande y significativa entre las variables peso e IMC sugiere que la inclusión de ambas variables en el modelo es inadecuada debido al alto nivel de redundancia en la información proporcionada por estas variables. Esto tiene sentido lógico ya que el IMC es una función del peso. El investigador ahora se enfrenta a la tarea de decidir cuál de las variables conservar para construir el modelo de regresión.

### **11.2 QUALITATIVE INDEPENDENT VARIABLES**

\
Las variables independientes consideradas en el análisis del Capítulo 10 fueron todas cuantitativas; es decir, produjeron valores numéricos que eran recuentos o mediciones en el sentido habitual de la palabra. Por ejemplo, algunas de las variables independientes utilizadas en nuestros ejemplos y ejercicios fueron la edad, el nivel de educación, la porosidad del colágeno y la resistencia a la tensión del colágeno. Sin embargo, con frecuencia es deseable utilizar una o más variables cualitativas como variables independientes en el modelo de regresión. Las variables cualitativas, se recordará, son aquellas variables cuyos "valores" son categorías y que transmiten el concepto de atributo en lugar de cantidad. La variable estado civil, por ejemplo, es una variable cualitativa cuyas categorías son "soltero", "casado", "viudo" y "divorciado". Otros ejemplos de variables cualitativas incluyen sexo (masculino o femenino), diagnóstico, raza, ocupación y estado de inmunidad a alguna enfermedad. En ciertas situaciones, un investigador puede sospechar que incluir una o más variables como estas en la ecuación de regresión contribuiría significativamente a la reducción de la suma de cuadrados del error y, por lo tanto, proporcionaría estimaciones más precisas de los parámetros de interés.

\
Supongamos, por ejemplo, que estamos estudiando la relación entre la variable dependiente presión arterial sistólica y las variables independientes peso y edad. También podríamos querer incluir la variable cualitativa sexo como una de las variables independientes. O supongamos que deseamos comprender mejor la naturaleza de la relación entre la capacidad pulmonar y otras variables relevantes. Las variables candidatas para su inclusión en el modelo podrían consistir en variables cuantitativas como la altura, el peso y la edad, así como variables cualitativas como el sexo, la zona de residencia (urbana, suburbana, rural) y el estado de tabaquismo (fumador actual, exfumador, nunca ha fumado).

**Variables ficticias** Para incorporar una variable independiente cualitativa en el modelo de regresión múltiple, es necesario cuantificarla de alguna manera. Esto se puede lograr mediante el uso de lo que se conoce como variables ficticias.

**DEFINITION**

Una variable ficticia es una variable que asume solo un número finito de valores (como 0 o 1) con el propósito de identificar las diferentes categorías de una variable cualitativa.

El término \"variable ficticia\" se utiliza para indicar que los valores numéricos (como 0 y 1) que asume la variable no tienen un significado cuantitativo, sino que se utilizan simplemente para identificar diferentes categorías de la variable cualitativa en cuestión. Las variables cualitativas a veces se denominan variables indicadoras y, cuando solo hay dos categorías, se las denomina variables dicotómicas.

A continuación se presentan algunos ejemplos de variables cualitativas y las variables ficticias utilizadas para cuantificarlas:

\
**Qualitative Variable**

\
Sex (male, female):

$$
x_1= \left\{ \begin{array}{cl}1 & \text{ for male } \\0 & \text{ for female }\end{array} \right.
$$

\
Place of residence (urban, rural, suburban):

$$
x_1= \left\{ \begin{array}{cl}1 & \text{ for urban } \\0 & \text{ for rural and suburban }\end{array} \right.
$$

\

$$
x_2= \left\{ \begin{array}{cl}1 & \text{ for rural } \\0 & \text{ for urban and suburban }\end{array} \right.
$$\

Smoking status \[current smoker, ex-smoker

(has not smoked for 5 years or less), ex-smoker

(has not smoked for more than 5 years), never

smoked\]:

$$
x_1= \left\{ \begin{array}{cl}1 & \text{ for current smoker } \\0 & \text{ for otherwise }\end{array} \right.
$$\

$$
x_2= \left\{ \begin{array}{cl}1 & \text{ for ex-smoker (\leq 5 years) } \\0 & \text{ for otherwise }\end{array} \right.
$$\

$$
x_3= \left\{ \begin{array}{cl}1 & \text{ for ex-smoker (\> 5 years) } \\0 & \text{ for otherwise }\end{array} \right.
$$\
\
\
Obsérvese en estos ejemplos que, cuando la variable cualitativa tiene k categorías, se deben definir k - 1 variables ficticias para que todas las categorías se codifiquen correctamente. Esta regla es aplicable a cualquier regresión múltiple que contenga una constante de intersección. La variable sexo, con dos categorías, se puede cuantificar mediante el uso de una sola variable ficticia, mientras que se requieren tres variables ficticias para cuantificar la variable estado de tabaquismo, que tiene cuatro categorías.

Los siguientes ejemplos ilustran algunos de los usos de las variables cualitativas en la regresión múltiple. En el primer ejemplo, suponemos que no hay interacción entre las variables independientes. Dado que el supuesto de que no hay interacción no es realista en muchos casos, ilustramos, en el segundo ejemplo, el análisis que resulta adecuado cuando se tiene en cuenta la interacción entre variables.

\
**EXAMPLE 11.2.1**

En un estudio de factores que se cree que están asociados con el peso al nacer, se seleccionó una muestra aleatoria simple de 100 registros de nacimientos del Registro de nacimientos de Carolina del Norte de 2001 (A-1). La Tabla 11.2.1 muestra, para tres variables, los datos extraídos de cada registro. Hay dos variables independientes: la duración de la gestación (semanas), que es cuantitativa, y el tabaquismo de la madre (fuma), una variable cualitativa. La variable dependiente es el peso al nacer (gramos).

\
TABLE 11.2.1 Data from a Simple Random Sample of 100 Births from the North Carolina Birth Registry, Example 11.2.1

\
**Solution:**

Para el análisis, cuantificamos el estado de tabaquismo mediante una variable ficticia que se codifica como 1 si la madre es fumadora y como 0 si no fuma. Los datos de la Tabla 11.2.1 se representan como un diagrama de dispersión en la Figura 11.2.1. El diagrama de dispersión sugiere que, en general, los períodos más largos de gestación se asocian con pesos al nacer más elevados.

Para obtener más información sobre la naturaleza de estos datos, podemos introducirlos en una computadora y emplear un programa adecuado para realizar análisis adicionales. Por ejemplo, introducimos las observaciones y1 = 3147, x 11 = 40, x 21 = 0, para el primer caso; y2 = 2977, x 12 = 41, x 22 = 0 para el segundo caso; y así sucesivamente. La figura 11.2.2 muestra el resultado de la computadora obtenido con el uso del programa de regresión múltiple MINITAB.

Vemos en la impresión que la ecuación de regresión múltiple es

yN j = bN 0 + bN 1x 1j + bN 2 x 2j

yN j = -1724 + 130x 1j - 294bN 2x 2j

\
(11.2.1)

\
Para observar el efecto en esta ecuación cuando deseamos considerar solo los nacimientos de madres fumadoras, hacemos x2j = 1. La ecuación entonces se convierte en

yN j = -1724 + 130x1j - 294112

= -2018 + 130x1j

\
(11.2.2)

\
\
que tiene una intersección con el eje $y$ de -2018 y una pendiente de 130. Nótese que la intersección con el eje y para la nueva ecuación es igual a 1bN 0 + bN 12 = 3-1724 + 1-29424 = -2018.

Consideremos ahora sólo los nacimientos de madres no fumadoras. Cuando hacemos que x 2 = 0, nuestra ecuación de regresión se reduce a

yNj = -1724 + 130x1j - 294102

= -1724 + 130x1j

(11.2.3)

La pendiente de esta ecuación es la misma que la pendiente de la ecuación para las madres fumadoras, pero los puntos de corte en $y$ son diferentes. El punto de corte en y para la ecuación asociada con las madres no fumadoras es mayor que el de las madres fumadoras. Estos resultados muestran que para esta muestra, los bebés nacidos de madres que no fuman pesaron, en promedio, más que los bebés nacidos de madres que sí fuman, cuando se toma en cuenta la duración de la gestación. La cantidad de la diferencia, en promedio, es de 294 gramos. Dicho de otra manera, podemos decir que para esta muestra, los bebés nacidos de madres que fuman pesaron, en promedio, 294 gramos menos que los bebés nacidos de madres que no fuman, cuando se toma en cuenta la duración de la gestación. La Figura 11.2.3 muestra el diagrama de dispersión de los datos originales junto con un gráfico de las dos líneas de regresión (Ecuaciones 11.2.2 y 11.2.3).

**EXAMPLE 11.2.2**

En este punto surge una pregunta sobre qué inferencias podemos hacer sobre la población muestreada en base a los resultados de la muestra obtenidos en el Ejemplo 11.2.1. En primer lugar, deseamos saber si la diferencia de muestra de 294 gramos es significativa. En otras palabras, ¿el tabaquismo tiene un efecto sobre el peso al nacer? Podemos responder a esta pregunta mediante el siguiente procedimiento de prueba de hipótesis.

**Solution**:

\
1. Data. The data are as given in Example 11.2.1.

2.  Supuestos. Suponemos que se cumplen los supuestos que fundamentan el análisis de regresión múltiple.
3.  Hypotheses. $H_0 : \beta_2 = 0; H_A : \beta_2 \neq 0$. Suppose we let $\alpha = .05$.
4.  Test statistic. The test statistic is $t = (\hat{\beta}_2-0)/s_{\hat{\beta}_2}$
5.  Distribución del estadístico de prueba. Cuando se cumplen los supuestos y $H_0$ es verdadera, el estadístico de prueba se distribuye como una t de Student con 97 grados de libertad.
6.  Regla de decisión. Rechazamos $H_0$ si el valor t calculado es mayor o igual a 1,9848 o menor o igual a -1,9848 (obtenido por interpolación).
7.  Cálculo del estadístico de prueba. El valor calculado del estadístico de prueba aparece en la Figura 11.2.2 como el cociente t del coeficiente asociado con la variable que aparece en la Columna 3 de la Tabla 11.2.1. Este coeficiente, por supuesto, es $\hat{\beta}_2$. Vemos que el t calculado es -2,17.
8.  Statistical decision. Since -2.17 6 \< -1.9848, we reject $H_0$.
9.  Conclusión. Concluimos que, en la población estudiada, el hecho de que las madres fumen o no está asociado con una reducción del peso de sus bebés al nacer.
10. $p$ value. For this test we have p = .033 from Figure 11.2.2.

\
**Un intervalo de confianza para** $\beta_2$ Dado que podemos concluir que en la población muestreada el estado de tabaquismo de las madres tiene un efecto sobre el peso al nacer de sus bebés, ahora podemos preguntarnos por la magnitud del efecto. Nuestra mejor estimación puntual de la diferencia promedio en el peso al nacer, cuando se toma en cuenta la duración de la gestación, es de 294 gramos a favor de los bebés nacidos de madres que no fuman. Podemos obtener una estimación de intervalo de la cantidad media de la diferencia utilizando la información de la impresión de la computadora mediante la siguiente expresión:

$$
\hat{\beta}_2 \pm ts_{\hat{\beta}_2}
$$\
Para un intervalo de confianza del 95 por ciento, tenemos

\$294.4 \\pm 1.9848(135.82)\$

$-563.9, -24.9$

\
Por lo tanto, estamos 95 por ciento seguros de que la diferencia está entre 564 gramos y 25 gramos.

**Ventajas de las variables ficticias** El lector puede haber supuesto correctamente que un análisis alternativo de los datos del Ejemplo 11.2.1 consistiría en ajustar dos ecuaciones de regresión separadas: una a la submuestra de madres que fuman y otra a la submuestra de las que no fuman. Sin embargo, este enfoque carece de algunas de las ventajas de la técnica de la variable ficticia y es un procedimiento menos deseable cuando este último procedimiento es válido. Si podemos justificar el supuesto de que las dos líneas de regresión separadas tienen la misma pendiente, podemos obtener una mejor estimación de esta pendiente común mediante el uso de variables ficticias, lo que implica agrupar los datos de las dos submuestras. En el Ejemplo 11.2.1, la estimación utilizando una variable ficticia se basa en un tamaño de muestra total de 100 observaciones, mientras que las estimaciones separadas se basarían en una muestra de 85 fumadores y solo 15 no fumadores. El enfoque de las variables ficticias también produce inferencias más precisas con respecto a otros parámetros, ya que hay más grados de libertad disponibles para el cálculo del cuadrado medio del error.

**Uso de variables ficticias: interacción presente** Ahora consideremos la situación en la que se supone que existe interacción entre las variables. Supongamos, por ejemplo, que tenemos dos variables independientes: una variable cuantitativa $X_1$ y una variable cualitativa con tres niveles de respuesta que dan como resultado las dos variables ficticias $X_2$ y $X_3$. El modelo, entonces, sería

$$
y_j = \beta_0 + \beta_1 X_{1j} + \beta_2 X_{2j} + \beta_3 X_{3j} + \beta_4 X_{1j} X_{2j} + \beta_5X_{1j} X_{3j} + \varepsilon_j
$$

(11.2.4)

donde $\beta_4 X_{1j} X_{2j}$ y $\beta_5 X_{1j} X_{3j}$ se denominan *términos de interacción* y representan la interacción entre las variables independientes cuantitativas y cualitativas. Nótese que no es necesario incluir en el modelo el término que contiene $X_{2j} X_{3j}$ ; siempre será cero porque cuando $X_2 = 1, X_3 = 0$, y cuando $X_3 = 1, X_2 = 0$. El modelo de la ecuación 11.2.4 permite una pendiente y una intersección con el eje Y diferentes para cada nivel de la variable cualitativa.

Supongamos que utilizamos codificación de variable ficticia para cuantificar la variable cualitativa de la siguiente manera:

$$
 X_2=\left\{\begin{matrix}
1 & \text{ for level 1 }  \\ 
0 & \text{ otherwise } \\
\end{matrix}\right.
$$\
\
$$
 X_3=\left\{\begin{matrix}
1 & \text{ for level 2 }  \\ 
0 & \text{ otherwise } \\
\end{matrix}\right.
$$

\
Las tres ecuaciones de regresión de muestra para los tres niveles de la variable cualitativa son, entonces, las siguientes:

**Level 1 (**$X_2=1, X_3 = 0$**)**

$$
\hat{y}_j = \hat{\beta}_0 + \hat{\beta}_1 x_{1j} + \hat{\beta}_2 (1) + \hat{\beta}_3 (0) + \hat{\beta}_4 x_{1j} (1) + \hat{\beta}_5 x_{1j} (0) \\
= \hat{\beta}_0 + \hat{\beta}_1 x_{1j} + \hat{\beta}_2 + \hat{\beta}_4 x_{1j} \\
= (\hat{\beta}_0 + \hat{\beta}_2) + (\hat{\beta}_1 + \hat{\beta}_4)x_{1j}
$$

(11.2.5)

**Level 2 (** $X_2 = 0, X_3 = 1$**)**

$$
\hat{y}_j = \hat{\beta}_0 + \hat{\beta}_1 x_{1j} + \hat{\beta}_2 (0) + \hat{\beta}_3 (1) + \hat{\beta}_4 x_{1j} (0) + \hat{\beta}_5 x_{1j} (1) \\
= \hat{\beta}_0 + \hat{\beta}_1 x_{1j} + \hat{\beta}_3 + \hat{\beta}_5 x_{1j} \\
= (\hat{\beta}_0 + \hat{\beta}_3) + (\hat{\beta}_1 + \hat{\beta}_5)x_{1j}
$$

(11.2.6)

\
**Level 3 (** $X_2 = 0, X_3 = 0$**)**

$$
\hat{y}_j = \hat{\beta}_0 + \hat{\beta}_1 x_{1j} + \hat{\beta}_2 (0) + \hat{\beta}_3 (0) + \hat{\beta}_4 x_{1j} (0) + \hat{\beta}_5 x_{1j} (0) \\
= \hat{\beta}_0 + \hat{\beta}_1 x_{1j}
$$

(11.2.7)

\

Let us illustrate these results by means of an example.

**EXAMPLE 11.2.3**

Un equipo de investigadores de salud mental desea comparar tres métodos (A, B y C) para tratar la depresión grave. También les gustaría estudiar la relación entre la edad y la eficacia del tratamiento, así como la interacción (si la hay) entre la edad y el tratamiento.

Cada miembro de una muestra aleatoria simple de 36 pacientes, comparables con respecto al diagnóstico y la gravedad de la depresión, fue asignado aleatoriamente para recibir el tratamiento A, B o C. Los resultados se muestran en la Tabla 11.2.2. La variable dependiente Y es la efectividad del tratamiento, la variable independiente cuantitativa X1 es la edad del paciente en el cumpleaños más cercano y la variable independiente tipo de tratamiento es una variable cualitativa que ocurre en tres niveles. La siguiente codificación de variable ficticia se utiliza para cuantificar la variable cualitativa:

$$
 X_2=\left\{\begin{matrix} 
1 & \text{ for treatment A } \\
0 & \text{ otherwise }  \\
\end{matrix}\right.
$$

$$
 X_3=\left\{\begin{matrix} 
1 & \text{ for treatment B } \\
0 & \text{ otherwise }  \\
\end{matrix}\right.
$$

\
El diagrama de dispersión de estos datos se muestra en la Figura 11.2.4. La Tabla 11.2.3 muestra los datos tal como se ingresaron en una computadora para su análisis. La Figura 11.2.5 contiene la impresión del análisis realizado con el programa de regresión múltiple MINITAB.

\
**Solution:**

Ahora examinemos la impresión para ver qué nos proporciona en cuanto a información sobre la naturaleza de las relaciones entre las variables. La ecuación de mínimos cuadrados es

$$
\hat{y}_j = 6.21 + 1.03 x_{1j} + 41.3 x_{2j} + 22.7 x_{3j} - .703 x_{1j} x_{2j} - .510 x_{1j} x_{3j}
$$\
\
Las tres ecuaciones de regresión para los tres tratamientos son las siguientes:

**Treatment A (Equation 11.2.5)**

$$
\hat{y}_j = (6.21 + 41.3) + (1.03 - .703) x_{1j} \\
= 47.51 + .327 x_{1j}
$$

**Treatment B (Equation 11.2.6)**

$$
\hat{y}_j = (6.21 + 22.7) + (1.03 - .510) x_{1j} \\
= 28.91 + .520 x_{1j}
$$

**Treatment C (Equation 11.2.7)**

$$
\hat{y}_j = 6.21 + 1.03 x_{1j}
$$

La figura 11.2.6 contiene el diagrama de dispersión de los datos originales junto con las ecuaciones de regresión para los tres tratamientos. La inspección visual de la figura 11.2.6 sugiere que los tratamientos A y B no difieren mucho con respecto a sus pendientes, pero sus intersecciones con el eje y son considerablemente diferentes. El gráfico sugiere que el tratamiento A es mejor que el tratamiento B para pacientes más jóvenes, pero la diferencia es menos dramática con pacientes mayores. El tratamiento C parece ser decididamente menos deseable que los tratamientos A y B para pacientes más jóvenes, pero es casi tan efectivo como el tratamiento B para pacientes mayores. Estas impresiones subjetivas son compatibles con la afirmación de que existe interacción entre los tratamientos y la edad.

**Procedimientos de inferencia**

Sin embargo, las relaciones que vemos en la Figura 11.2.6 son resultados de muestra. ¿Qué podemos concluir acerca de la población de la que se extrajo la muestra?

Para obtener la respuesta, observemos las relaciones t en la impresión de la computadora en la Figura 11.2.5.

Cada uno de estos es la estadística de prueba.

$$
t = \frac{\hat{\beta}_i - 0}{s_{\hat{\beta}_i}}
$$\
\
para probar $H_0 : \beta_i = 0$. Vemos por la Ecuación 11.2.5 que la intersección con el eje y de la línea de regresión para el tratamiento A es igual a $\hat{\beta}0 + \hat{\beta}2$. Dado que la razón t de 8,12 para probar $H_0 : \beta_2 = 0$ es mayor que la t crítica de 2,0423 (para a = .05), podemos rechazar $H_0$ que $\beta_2 = 0$ y concluir que la intersección con el eje y de la línea de regresión poblacional para el tratamiento A es diferente de la intersección con el eje y de la línea de regresión poblacional para el tratamiento C, que tiene una intersección con el eje y de $\beta_0$. De manera similar, dado que la razón t de 4,46 para probar $H_0 : \beta_3 = 0$ también es mayor que la t crítica de 2,0423, podemos concluir (en el nivel de significancia .05) que la intersección con el eje y de la línea de regresión poblacional para el tratamiento B también es diferente de la intersección con el eje y de la línea de regresión poblacional para el tratamiento C. (Véase la intersección con el eje y de la ecuación 11.2.6.)

\
Ahora consideremos las pendientes. Vemos por la Ecuación 11.2.5 que la pendiente de la línea de regresión para el tratamiento A es igual a $\hat{\beta}_1$ (la pendiente de la línea para el tratamiento C) + $\hat{\beta}_4$. Puesto que el cociente t de -6,45 para probar $H_0 : \beta_4 = 0$ es menor que el t crítico de -2,0423, podemos concluir (para a = .05) que las pendientes de las líneas de regresión poblacional para los tratamientos A y C son diferentes. De manera similar, puesto que el cociente t calculado para probar $H_0 : \beta_5 = 0$ también es menor que -2,0423, concluimos (para $\alpha = .05$) que las líneas de regresión poblacional para los tratamientos B y C tienen pendientes diferentes (ver la pendiente de la Ecuación 11.2.6). Por lo tanto, concluimos que hay interacción entre la edad y el tipo de tratamiento. Esto se refleja en una falta de paralelismo entre las líneas de regresión en la Figura 11.2.6.

Otra pregunta de interés es la siguiente: ¿la pendiente de la línea de regresión poblacional para el tratamiento A es diferente de la pendiente de la línea de regresión poblacional para el tratamiento B? Para responder a esta pregunta se requieren técnicas computacionales que van más allá del alcance de este texto. Se recomienda al lector interesado consultar libros dedicados específicamente al análisis de regresión.

En la Sección 10.4 se advirtió al lector que existen problemas al realizar múltiples inferencias a partir de los mismos datos de muestra. Nuevamente, existen libros sobre análisis de regresión que pueden consultarse para conocer los procedimientos que se deben seguir cuando se desean realizar múltiples inferencias, como las que se analizan en esta sección.

\
Hemos analizado sólo dos situaciones en las que resulta adecuado el uso de variables ficticias. En determinadas circunstancias, pueden resultar adecuados modelos más complejos que impliquen el uso de una o más variables independientes cualitativas en presencia de dos o más variables cuantitativas. En los numerosos libros dedicados al tema del análisis de regresión múltiple se analizan modelos más complejos.

**EXERCISES**

\
Para cada ejercicio haga lo siguiente:

\
(a) Draw a scatter diagram of the data using different symbols for the different categorical variables.

\(b\) Use dummy variable coding and regression to analyze the data.

\(c\) Perform appropriate hypothesis tests and construct appropriate confidence intervals using your choice of significance and confidence levels.

\(d\) Find the p value for each test that you perform.

\
11.2.1 En los sujetos sometidos a trasplantes de células madre, las células dendríticas (CD) son células presentadoras de antígenos que son fundamentales para la generación de respuestas inmunológicas tumorales. Bolwell et al. (A-2) estudiaron las CD linfoides en 44 sujetos sometidos a trasplante autólogo de células madre. La variable de resultado es la concentración de células CD2 medida mediante citometría de flujo. Una de las variables independientes es la edad del sujeto (años) y la segunda variable independiente es el método de movilización. Durante la quimioterapia, 11 sujetos recibieron movilizador de factor estimulante de colonias de granulocitos (G-CSF) (mg/kg/día) y 33 recibieron etopósido (2 g\>m2). El movilizador es un tipo de célula progenitora sanguínea que desencadena la formación de las células CD. Los resultados fueron los siguientes:

11.2.2 Según Pandey et al. (A-3), el carcinoma de vesícula biliar no es infrecuente. Uno de los principales factores de riesgo del cáncer de vesícula biliar es la colelitiasis, la presencia asintomática de cálculos en la vesícula biliar. Los investigadores realizaron un estudio de casos y controles de 50 sujetos con cáncer de vesícula biliar y 50 sujetos con colelitiasis. De interés fue la concentración de productos de peroxidación lipídica en la bilis de la vesícula biliar, una condición que puede dar lugar al cáncer de vesícula biliar. El producto de peroxidación lipídica melonaldehído (MDA, mg/mg) se utilizó para medir la peroxidación lipídica. Una de las variables independientes consideradas fue la concentración de citocromo P-450 (CYTO, nmol/mg). Los investigadores utilizaron el estado de la enfermedad (cáncer de vesícula biliar frente a colelitiasis) y la concentración de citocromo P-450 para predecir el MDA. Se recopilaron los siguientes datos.

11.2.3 El objetivo de un estudio realizado por Krantz et al. (A-4) fue investigar los efectos relacionados con la dosis de metadona en sujetos con torsades de pointes, una taquicardia ventricular polimórfica. En el estudio de 17 sujetos, 10 eran hombres (sexo = 0) y siete eran mujeres (sexo = 1). La variable de resultado es el intervalo QTc, una medida del riesgo de arritmia. La otra variable independiente, además del sexo, fue la dosis de metadona (mg/día). Las mediciones de estas variables para los 17 sujetos fueron las siguientes.

11.2.4 Consulte el Ejercicio 9.7.2, que describe la investigación de Reiss et al. (A-5), quienes recogieron muestras de 90 pacientes y midieron el tiempo de tromboplastina parcial (aPTT) utilizando dos métodos diferentes: el ensayo en el punto de atención CoaguChek y el ensayo estándar de laboratorio en el hospital. Los sujetos también fueron clasificados según su estado de medicación: 30 recibieron heparina sola, 30 recibieron heparina con warfarina y 30 recibieron warfarina y enoxaparina. Los datos son los siguientes.\

Utilice la regresión múltiple para predecir el aPTT hospitalario a partir del nivel de aPTT de CoaguCheck, así como de la medicación recibida. ¿Es útil el conocimiento de la medicación para la predicción? Sea a = .05 para todas las pruebas.

### 11.3 PROCEDIMIENTOS DE SELECCIÓN DE VARIABLES

\
Los investigadores de las ciencias de la salud que contemplan el uso del análisis de regresión múltiple para resolver problemas suelen descubrir que tienen una gran cantidad de variables de las cuales seleccionar las variables independientes que se emplearán como predictores de la variable dependiente. Dichos investigadores querrán incluir en su modelo tantas variables como sea posible para maximizar la capacidad predictiva del modelo. Sin embargo, el investigador debe darse cuenta de que agregar otra variable independiente a un conjunto de variables independientes siempre aumenta el coeficiente de determinación R2. Por lo tanto, las variables independientes no deben agregarse al modelo indiscriminadamente, sino solo por una buena razón. En la mayoría de las situaciones, por ejemplo, algunas variables predictoras potenciales son más caras que otras en términos de costos de recopilación de datos. Por lo tanto, el investigador consciente de los costos no querrá incluir una variable costosa en un modelo a menos que haya evidencia de que hace una contribución valiosa a la capacidad predictiva del modelo.

El investigador que desee utilizar el análisis de regresión múltiple de la manera más eficaz debe ser capaz de emplear alguna estrategia para hacer selecciones inteligentes entre las posibles variables predictoras disponibles. Actualmente se utilizan muchas de esas estrategias y cada una tiene sus defensores. Las estrategias varían en términos de complejidad y del tedio que implica su uso. Desafortunadamente, las estrategias no siempre conducen a la misma solución cuando se aplican al mismo problema.

\
**Regresión por pasos** Quizás la estrategia más utilizada para seleccionar variables independientes para un modelo de regresión múltiple es el procedimiento por pasos. El procedimiento consta de una serie de pasos. En cada paso del procedimiento se evalúa cada variable del modelo para ver si, según criterios específicos, debería permanecer en el modelo.

\
Supongamos, por ejemplo, que deseamos realizar una regresión por pasos para un modelo que contiene k variables predictoras. Se calcula la medida de criterio para cada variable. De todas las variables que no satisfacen el criterio de inclusión en el modelo, se elimina del modelo la que menos lo satisface. Si se elimina una variable en este paso, se calcula la ecuación de regresión para el modelo más pequeño y se calcula la medida de criterio para cada variable que ahora está en el modelo. Si alguna de estas variables no satisface el criterio de inclusión en el modelo, se elimina la que menos lo satisface. Si se elimina una variable en este paso, la variable que se eliminó en el primer paso se vuelve a ingresar en el modelo y continúa el procedimiento de evaluación. Este proceso continúa hasta que no se puedan ingresar o eliminar más variables.

La naturaleza del procedimiento paso a paso es tal que, aunque una variable puede eliminarse del modelo en un paso, se evalúa su posible reingreso al modelo en pasos posteriores.

\
Por ejemplo, el procedimiento STEPWISE de MINITAB utiliza la estadística F asociada como criterio de evaluación para decidir si se debe eliminar o agregar una variable al modelo. A menos que se especifique lo contrario, el valor de corte es F = 4. La impresión de los resultados de STEPWISE contiene estadísticas t (la raíz cuadrada de F ) en lugar de estadísticas F. En cada paso, MINITAB calcula una estadística F para cada variable que exista en el modelo. Si la estadística F de cualquiera de estas variables es menor que el valor de corte especificado (4 si no se especifica ningún otro valor), la variable con la F más pequeña se elimina del modelo. La ecuación de regresión se reajusta para el modelo reducido, se imprimen los resultados y el procedimiento pasa al siguiente paso. Si no se puede eliminar ninguna variable, el procedimiento intenta agregar una variable. Se calcula una estadística F para cada variable que no exista en el modelo. De estas variables, se agrega la que tenga la estadística F asociada más grande, siempre que su estadística F sea mayor que el valor de corte especificado (4 si no se especifica ningún otro valor). La ecuación de regresión se reajusta para el nuevo modelo, se imprimen los resultados y el procedimiento continúa con el siguiente paso. El procedimiento se detiene cuando no se puede agregar ni eliminar ninguna variable.

El siguiente ejemplo ilustra el uso del procedimiento paso a paso para seleccionar variables para un modelo de regresión múltiple.

\
\

**EXAMPLE 11.3.1**

Un director de enfermería desea utilizar las características personales de las enfermeras para desarrollar un modelo de regresión para predecir el desempeño laboral (JOBPER). Las siguientes variables están disponibles para elegir las variables independientes que se incluirán en el modelo:

$X_1$ = assertiveness 1ASRV2

$X_2$ = enthusiasm 1ENTH2

$X_3$ = ambition 1AMB2

$X_4$ = communication skills 1COMM2

$X_5$ = problem-solving skills 1PROB2

$X_6$ = initiative 1INIT2

Deseamos utilizar el procedimiento paso a paso para seleccionar variables independientes de aquellas disponibles en la tabla para construir un modelo de regresión múltiple para predecir el desempeño laboral.

**Solution:**

\
Table 11.3.1 shows the measurements taken on the dependent variable, JOBPER, and each of the six independent variables for a sample of 30 nurses.

\

TABLE 11.3.1 Measurements on Seven Variables for Examples 11.3.1

\
Utilizamos MINITAB para obtener un modelo útil mediante el procedimiento paso a paso. Las observaciones sobre la variable dependiente desempeño laboral (JOBPER) y las seis variables independientes candidatas se almacenan en las columnas 1 a 7 de MINITAB, respectivamente. La figura 11.3.1 muestra el procedimiento MINITAB apropiado y la impresión de los resultados.

\
Para obtener los resultados de la Figura 11.3.1, los valores de F para ingresar y F para eliminar se establecieron automáticamente en 4. En el paso 1 no hay variables que se deban considerar para la eliminación del modelo. La variable AMB (columna 4) tiene la estadística F asociada más grande, que es $F = (9.74)^2 = 94.8676$. Como 94.8676 es mayor que 4, se agrega AMB al modelo. En el paso 2, la variable INIT (columna 7) califica para su adición al modelo ya que su F asociada de $(-2.2)^2 = 4.84$ es mayor que 4 y es la variable con la estadística F asociada más grande. Se agrega al modelo. Después del paso 2, no se pudo agregar ni eliminar ninguna otra variable y el procedimiento se detuvo. Vemos, entonces, que el modelo elegido por el procedimiento paso a paso es un modelo de dos variables independientes con AMB e INIT como variables independientes. La ecuación de regresión estimada es

$$
\hat{y} = 31.96 + .787 x_3 - .45 x_6
$$\
\
Para cambiar el criterio para permitir que una variable ingrese al modelo de 4 a otro valor K, haga clic en Opciones y luego escriba el valor deseado de K en el cuadro Ingresar. El nuevo estadístico del criterio F, entonces, es K en lugar de 4. Para cambiar el criterio para eliminar una variable del modelo de 4 a otro valor K, haga clic en Opciones y luego escriba el valor deseado de K en el cuadro Eliminar. Debemos elegir que K para ingresar sea mayor o igual que K para eliminar.

Aunque el procedimiento de selección por pasos es una técnica común empleada por los investigadores, existen otros métodos disponibles. A continuación se presenta una breve descripción de dos de estas herramientas. El modelo final obtenido mediante cada uno de estos procedimientos es el mismo modelo que se encontró utilizando el procedimiento por pasos en el Ejemplo 11.3.1.

**Selección hacia adelante** Esta estrategia está estrechamente relacionada con el procedimiento de regresión por pasos. Este método construye un modelo utilizando correlaciones. Se conservan las variables que cumplen los criterios de inclusión, como en la selección por pasos. La primera variable que se introduce en el modelo es la que tiene la correlación más alta con la variable dependiente. Si esta variable cumple con el criterio de inclusión, se conserva. La siguiente variable que se considera para su inclusión es la que tiene la correlación parcial más alta con la variable dependiente. Si cumple con los criterios de inclusión, se conserva. Este procedimiento continúa hasta que se hayan considerado todas las variables independientes. El modelo final contiene todas las variables independientes que cumplen con los criterios de inclusión.

**Eliminación hacia atrás** Este procedimiento de construcción de modelos comienza con todas las variables del modelo. Esta estrategia también construye un modelo utilizando correlaciones y un criterio de inclusión predeterminado basado en la estadística F. La primera variable que se considera para eliminar del modelo es la que tiene el coeficiente de correlación parcial más pequeño. Si esta variable no cumple con el criterio de inclusión, se elimina del modelo. La siguiente variable que se considera para eliminar es la que tiene la siguiente correlación parcial más baja. Se eliminará si no cumple con el criterio de inclusión. Este procedimiento continúa hasta que se hayan considerado todas las variables para su eliminación. El modelo final contiene todas las variables independientes que cumplen con los criterios de inclusión.

**EXERCISES**

11.3.1 Consulte los datos del Ejercicio 10.3.2 informados por Son et al. (A-6), quienes estudiaron el cuidado familiar en Corea de adultos mayores con demencia. La variable de resultado, la carga del cuidador (BURDEN), se midió mediante el Inventario de Carga Coreano (KBI), donde las puntuaciones oscilaron entre 28 y 140, y las puntuaciones más altas indican una carga mayor. Realice un análisis de regresión por pasos sobre las siguientes variables independientes informadas por los investigadores:

CGAGE: caregiver age (years)

CGINCOME: caregiver income (Won-Korean currency)

CGDUR: caregiver-duration of caregiving (month)

ADL: total activities of daily living where low scores indicate the elderly perform activities independently.

MEM: memory and behavioral problems with higher scores indicating more problems.

COG: cognitive impairment with lower scores indicating a greater degree of cognitive impair-

ment.

SOCIALSU: total score of perceived social support (25--175, higher values indicating more support). The reported data are as follows.

\
11.3.2 Machiel Naeije (A-7) identifica variables útiles para predecir la apertura bucal máxima (AMO, milímetros) en 35 voluntarios sanos. Las variables examinadas fueron:

\
AGE:

DOWN_CON:

FORW_CON:

Gender:

MAN_LENG:

MAN_WIDT:

years

downward condylar translation, mm

forward condylar translation, mm

0 " Female, 1 " Male

mandibular length, mm

mandibular width, mm

\

Use the following reported measurements to perform a stepwise regression.

11.3.3 Uno de los objetivos de un estudio realizado por Connor et al. (A-8) fue examinar la agresión reactiva entre niños y adolescentes derivados a un centro de tratamiento residencial. Los investigadores utilizaron la Escala de Calificación Proactiva/Reactiva, obtenida presentando tres afirmaciones a los médicos que examinaron a los sujetos. Los encuestados respondieron utilizando una escala del 1 al 5, donde 5 indica que la afirmación casi siempre se aplicaba al niño. Un ejemplo de una afirmación de agresión reactiva es: \"Cuando este niño ha sido objeto de burlas o amenazas, se enoja fácilmente y contraataca\". La puntuación reactiva fue la respuesta media a tres afirmaciones de este tipo. Con esta variable como variable de resultado, los investigadores también examinaron lo siguiente: AGE (años), VERBALIQ (CI verbal), STIM (uso de estimulantes), AGEABUSE (edad en la que se abusó por primera vez), CTQ (una medida de hiperactividad en la que las puntuaciones más altas indican una hiperactividad más alta), TOTALHOS (hostilidad total medida por un evaluador, donde los números más altos indican una hostilidad más alta). Realice una regresión por pasos para encontrar las variables más útiles para predecir la agresión reactiva en la siguiente muestra de 68 sujetos.

### **1 .4 LOGISTIC REGRESSION**

\
Hasta ahora, nuestra discusión del análisis de regresión se ha limitado a aquellas situaciones en las que la variable dependiente es una variable continua, como el peso, la presión arterial o los niveles plasmáticos de alguna hormona. Gran parte de la investigación en el campo de las ciencias de la salud está motivada por el deseo de describir, comprender y hacer uso de la relación entre las variables independientes y una variable dependiente (o de resultado) que es discreta. Son particularmente abundantes las circunstancias en las que la variable de resultado es dicotómica. Recordemos que una variable dicotómica es una variable que puede asumir solo uno de dos valores mutuamente excluyentes. Estos valores suelen codificarse como Y = 1 para un éxito e Y = 0 para un fracaso.

\
Las variables dicotómicas incluyen aquellas cuyos dos valores posibles son categorías como muerto-no muerto; curado-no curado; enfermedad ocurrida-enfermedad no ocurrida; y fumador-no fumador. El profesional de las ciencias de la salud que se dedica a la investigación o necesita entender los resultados de la investigación realizada por otros encontrará ventajoso tener, al menos, un conocimiento básico de la regresión logística, el tipo de análisis de regresión que se emplea habitualmente cuando la variable dependiente es dicotómica. El propósito de la presente discusión es proporcionar al lector este nivel de comprensión. Limitaremos nuestra presentación al caso en el que sólo hay una variable independiente que puede ser continua o dicotómica.

**El modelo de regresión logística** Recuerde que en el Capítulo 9 nos referimos al análisis de regresión que involucra sólo dos variables como análisis de regresión lineal simple. El modelo de regresión lineal simple se expresó mediante la ecuación

$$
y = \beta_0 + \beta_1 x + \varepsilon
$$

(11.4.1)

donde $y$ es un valor observado arbitrario de la variable dependiente continua. Cuando el valor observado de Y es $\mu_{y|x}$ , la media de una subpoblación de valores de Y para un valor dado de X, la cantidad $\varepsilon$, la diferencia entre el Y observado y la línea de regresión (ver Figura 9.2.1) es cero, y podemos escribir la Ecuación 11.4.1 como

$$
\mu_{y|x} = \beta_0 + \beta_1 x
$$\
\
\

which may also be written as

$$
E_{(y|x)} = \beta_0 + \beta_1 x
$$\

Generalmente, el lado derecho de las ecuaciones 11.4.1 a 11.4.3 puede asumir cualquier valor entre menos infinito y más infinito.

Aunque sólo intervienen dos variables, el modelo de regresión lineal simple no es adecuado cuando Y es una variable dicotómica porque el valor esperado (o media) de Y es la probabilidad de que Y = 1 y, por lo tanto, está limitado al rango de 0 a 1, inclusive. Las ecuaciones 11.4.1 a 11.4.3, entonces, son incompatibles con la realidad de la situación.

\
Si hacemos que p = P(Y = 1), entonces la razón p\\(1 - p) puede tomar valores entre 0 y más infinito. Además, el logaritmo natural (ln) de p\\(1 - p) puede tomar valores entre menos infinito y más infinito, al igual que el lado derecho de las ecuaciones 11.4.1 a 11.4.3. Por lo tanto, podemos escribir

$$
\ln [\frac{p}{1-p}] = \beta_0 + \beta_1 x
$$\
\
(11.4.4)

\
La ecuación 11.4.4 se denomina modelo de regresión logística porque la transformación de $\mu_{y|x}$ (es decir, p) a ln\[p/(1 - p)\] se denomina transformación logit. La ecuación 11.4.4 también se puede escribir como

$$
p = \frac{\exp (\beta_0 + \beta_1 x}{1 + \exp (\beta_0 + \beta_1 x)}
$$\
\

in which exp is the inverse of the natural logarithm.

\

El modelo de regresión logística se utiliza ampliamente en la investigación en ciencias de la salud. Por ejemplo, los epidemiólogos lo utilizan con frecuencia como modelo para la probabilidad (interpretada como el riesgo) de que un individuo contraiga una enfermedad durante un período de tiempo específico durante el cual está expuesto a una condición (llamada factor de riesgo) que se sabe o se sospecha que está asociada con la enfermedad.

**Regresión logística: variable independiente dicotómica** La situación más simple en la que se puede aplicar la regresión logística es aquella en la que tanto la variable dependiente como la independiente son dicotómicas. Los valores de la variable dependiente (o de resultado) suelen indicar si un sujeto adquirió o no una enfermedad o si el sujeto murió o no. Los valores de la variable independiente indican el estado del sujeto en relación con la presencia o ausencia de algún factor de riesgo. En la discusión que sigue, suponemos que las dicotomías de las dos variables están codificadas como 0 y 1. Cuando este es el caso, las variables pueden clasificarse de forma cruzada en una tabla, como la Tabla 11.4.1, que contiene dos filas y dos columnas. Las celdas de la tabla contienen las frecuencias de aparición de todos los pares posibles de valores de las dos variables: (1, 1), (1, 0), (0, 1) y (0, 0).

Un objetivo del análisis de los datos que cumplen estos criterios es una estadística conocida como razón de probabilidades. Para entender el concepto de razón de probabilidades, debemos entender el término probabilidades, que es utilizado con frecuencia por quienes realizan apuestas sobre los resultados de eventos deportivos o participan en otros tipos de actividades de juego. Utilizando la terminología de probabilidad, podemos definir las probabilidades de la siguiente manera.

\
**DEFINITION**

Las probabilidades de éxito son la relación entre la probabilidad de éxito y la probabilidad de fracaso.

\
La razón de probabilidades es una medida de cuánto mayores (o menores) son las probabilidades de que los sujetos que poseen el factor de riesgo experimenten un resultado particular. Esta conclusión supone que el resultado es un evento poco común. Por ejemplo, cuando el resultado es contraer una enfermedad, la interpretación de la razón de probabilidades supone que la enfermedad es poco común.

Supongamos, por ejemplo, que la variable de resultado es la aparición o no de cáncer de piel y que la variable independiente (o factor de riesgo) son los altos niveles de exposición al sol. El análisis de esos datos recopilados sobre una muestra de sujetos podría arrojar un cociente de probabilidades de 2, lo que indica que las probabilidades de padecer cáncer de piel son dos veces mayores entre los sujetos con altos niveles de exposición al sol que entre los sujetos sin altos niveles de exposición.

\
Los paquetes de software informáticos que realizan regresión logística suelen proporcionar como parte de sus resultados estimaciones de $\beta_0$ y $\beta_1$ y el valor numérico de la razón de probabilidades. Resulta que la razón de probabilidades es igual a $\exp(\beta_1)$.

\
**EXAMPLE 11.4.1**

LaMont et al. (A-9) realizaron pruebas para detectar la enfermedad coronaria obstructiva (EOC) en 113 hombres y 35 mujeres que se quejaron de dolor en el pecho o un posible equivalente a su médico de atención primaria. La Tabla 11.4.2 muestra la clasificación cruzada de la EOC con el género. Deseamos utilizar un análisis de regresión logística para determinar cuánto mayores son las probabilidades de encontrar EOC entre los hombres que entre las mujeres.

**Solution:**

Podemos utilizar el paquete de software SAS® para analizar estos datos. La variable independiente es el género y la variable dependiente es el estado con respecto a la presencia de enfermedad coronaria obstructiva (EOC). El uso del comando SAS® PROC LOGIST genera, como parte de la salida resultante, las estadísticas que se muestran en la Figura 11.4.1.

\
Vemos que la estimación de a es -1,4773 y la estimación de b 1 es 1,7649. La razón de probabilidades estimada es, entonces, OR = exp11,76492 = 5,84. Por lo tanto, estimamos que las probabilidades de encontrar un caso de enfermedad coronaria obstructiva son casi seis veces mayores entre los hombres que entre las mujeres.

**Regresión logística: variable independiente continua** Consideremos ahora la situación en la que tenemos una variable dependiente dicotómica y una variable independiente continua. Supondremos que se dispone de una computadora para realizar los cálculos. En consecuencia, nuestro análisis se centrará en la evaluación de la idoneidad del modelo como representación de los datos disponibles, la interpretación de los elementos clave de la impresión de la computadora y el uso de los resultados para responder a preguntas relevantes sobre la relación entre las dos variables.

\
**EXAMPLE 11.4.2**

Según Gallagher et al. (A-10), los programas de rehabilitación cardíaca ofrecen \"información, apoyo y seguimiento para el retorno a las actividades, el manejo de los síntomas y la modificación de los factores de riesgo\". Los investigadores llevaron a cabo un estudio para identificar entre las mujeres los factores que se asocian con la participación en dichos programas. Los datos de la Tabla 11.4.3 corresponden a las edades de 185 mujeres dadas de alta de un hospital de Australia que cumplían los criterios de elegibilidad que incluían el alta por infarto de miocardio, cirugía de bypass arterial, angioplastia o colocación de stent. Deseamos utilizar estos datos para obtener información sobre la relación entre la edad (años) y la participación en un programa de rehabilitación cardíaca (ATT = 1, si participó, y ATT = 0, si no). También deseamos saber si podemos utilizar los resultados de nuestro análisis para predecir la probabilidad de participación de una mujer si conocemos su edad.

**Solution**:

La variable independiente es la variable continua edad (AGE), y la variable dependiente o de respuesta es el estado con respecto a la asistencia a un programa de rehabilitación cardíaca. La variable dependiente es una variable dicotómica que puede asumir uno de dos valores: 0 = no asistió y 1 = asistió. Utilizamos el paquete de software SAS® para analizar los datos. El comando SAS® es PROC LOGISTIC, pero si deseamos predecir la asistencia al programa cardíaco, debemos utilizar la opción \"descendente\" con PROC LOGISTIC. (Cuando desee predecir el resultado etiquetado como \"1\" de la variable dependiente, utilice la \"opción descendente\" en SAS®. Consulte la documentación de SAS® para obtener más detalles). En la Figura 11.4.2 se muestra una impresión parcial del análisis.

\
The slope of our regression is -.0379, and the intercept is 1.8744. The regression equation, then, is

$$
\hat{y}_i = 1.8744 - .0379 x_i
$$\

where $\hat{y}_i = \ln[\hat{p}_i / (1 - \hat{p}_i)]$ and $\hat{p}_i$ is the predicted probability of attending cardiac rehabilitation for a woman aged $x_i$.

\
**Test of** $H_0$ **that** $\beta_1 =  0$

\
Llegamos a una conclusión sobre la adecuación del modelo logístico probando la hipótesis nula de que la pendiente de la línea de regresión es cero. El estadístico de prueba es $z = \hat{\beta}_1 / s_{\hat{\beta}_1}$ donde z es el estadístico normal estándar, $\hat{\beta}_1$ es la pendiente de la muestra 1-.03792, y $s_{\hat{\beta}_1}$ es su error estándar (.0146) como se muestra en la Figura 11.4.2. A partir de estos números calculamos z = -.0379/.0146 = -2.5959, que tiene un valor p bilateral asociado de .0094. Concluimos, por lo tanto, que el modelo logístico es adecuado. El cuadrado de z es chi-cuadrado con 1 grado de libertad, un estadístico que se muestra en la Figura 11.4.2.

**Using the Logistic Regression to Estimate p**

Podemos utilizar la ecuación 11.4.5 y los resultados de nuestro análisis para estimar p, la probabilidad de que una mujer de una edad determinada (dentro del rango de edades representado por los datos) asista a un programa de rehabilitación cardíaca. Supongamos, por ejemplo, que deseamos estimar la probabilidad de que una mujer de 50 años participe en un programa de rehabilitación. Sustituyendo 50 y los resultados que se muestran en la Figura 11.4.2 en la ecuación 11.4.5 obtenemos

$$
\hat{p} = \frac{\exp[1.8744 - (.0379)(50)]}{1 + \exp[1.8744 - (.0379)(50)]}= .49485
$$\
\
SAS® calcula las probabilidades estimadas para los valores dados de X. Podemos ver las probabilidades estimadas de asistir a programas de rehabilitación cardíaca para el rango de edad de los sujetos inscritos en el estudio en la Figura 11.4.3. Como la pendiente era negativa, vemos una probabilidad decreciente de asistir a un programa de rehabilitación cardíaca para mujeres mayores.

\
\

**Multiple Logistic Regression** \

Los profesionales de la regresión logística múltiple suelen estar interesados ​​en las relaciones de varias variables independientes con una variable de respuesta. Estas variables independientes pueden ser continuas o discretas o una combinación de ambas.

Los modelos logísticos múltiples se construyen ampliando las ecuaciones 11.4.1 a 11.4.4. Si comenzamos con la ecuación 11.4.4, la regresión logística múltiple se puede representar como

$$
\ln [\frac{p}{1-p}] = \beta_0 + \beta_1 x_{1j} + \beta_2 x_{2j} + ... + \beta_k x_{kj}
$$\
\

(11.4.6)

\

Using the logit transformation, we now have

$$
p = \frac{\exp (\beta_0 + \beta_1 x_{1j} + \beta_2 x_{2j} + ... + \beta_k x_{kj})}{1 +\exp (\beta_0 + \beta_1 x_{1j} + \beta_2 x_{2j} + ... + \beta_k x_{kj})}
$$

p =

exp1b 0 + b 1x 1j + b 2x 2j + Á + b k x kj2

1 + exp1b 0 + b 1x 1j + b 2x 2j + Á + b k x kj2

(11.4.7)

\
**EXAMPLE 11.4.3**

Considere los datos presentados en el Ejercicio de Revisión 24. En este estudio de Fils-Aime et al. (A-21), se recopilaron y clasificaron datos con respecto al consumo de alcohol. Los sujetos se clasificaron como de inicio temprano (% 25 años) o tardío (\$ 25 años) de consumo excesivo de alcohol.

\
También se obtuvieron los niveles de triptófano (TRYPT) y de ácido 5-hidroxiindolacético (5-HIAA) en el líquido cefalorraquídeo (LCR).

**Solution:**

Las variables independientes son las concentraciones de TRYPT y 5-HIAA, y la variable dependiente es la respuesta dicotómica para el inicio del consumo excesivo de alcohol. Utilizamos el software SPSS para analizar los datos. El resultado se presenta en la Figura 11.4.3.

\
The equation can be written as

$$
\hat{y}_i = 2.076 - .013 x_{1j} + 0 x_{2j}
$$\

Note that the coefficient for TRYPT is 0, and therefore it is not playing a role in the model.

\
**Test of** $H_0$ **that** $\beta_1 =  0$

Las pruebas de significancia de los coeficientes de regresión se pueden obtener directamente de la Figura 11.4.3. Nótese que tanto la constante (intersección) como las variables 5-HIAA son significativas en el modelo (ambas tienen valores p, indicados como \"Sig.\" en la tabla, \< .05); sin embargo, TRYPT no es significativo y por lo tanto no necesita estar en el modelo, lo que sugiere que no es útil para identificar a aquellos participantes del estudio con inicio temprano o tardío del alcoholismo.

Como se indicó anteriormente, las probabilidades se pueden obtener fácilmente utilizando la ecuación 11.4.7 y sustituyendo los valores obtenidos del análisis.

\
**Polytomous Logistic Regression**

Regresión logística politómica Hasta ahora hemos limitado nuestra discusión a situaciones en las que hay una variable de respuesta dicotómica (p. ej., exitosa o no exitosa). A menudo tenemos una situación en la que múltiples categorías conforman la respuesta. Podemos, por ejemplo, tener sujetos que se clasifican como positivos, negativos e indeterminados para una enfermedad dada (una respuesta politómica estándar). También puede haber momentos en los que tenemos una variable de respuesta que está ordenada. Podemos, por ejemplo, clasificar a nuestros sujetos por IMC como bajo peso, peso ideal, sobrepeso u obesidad (una respuesta politómica ordinal). El proceso de modelado es ligeramente más complejo y requiere el uso de un programa de computadora. Para aquellos interesados ​​en explorar estos valiosos métodos más a fondo, recomendamos el libro de Hosmer y Lemeshow (1).

**Lectura adicional**

Hemos analizado únicamente los conceptos y aplicaciones básicos de la regresión logística. La técnica tiene una aplicación mucho más amplia. El análisis de regresión por pasos se puede utilizar con la regresión logística. También existen técnicas disponibles para construir intervalos de confianza para los odds ratios. El lector que desee aprender más sobre la regresión logística puede consultar los libros de Hosmer y Lemeshow (1) y Kleinbaum (2).

**EXERCISES**

11.4.1 En un estudio sobre la victimización violenta de mujeres y hombres, Porcerelli et al. (A-11) recopilaron información de 679 mujeres y 345 hombres de 18 a 64 años en varios centros de medicina familiar en el área metropolitana de Detroit. Los pacientes completaron un cuestionario de antecedentes médicos que incluía una pregunta sobre la victimización. La siguiente tabla muestra los sujetos de la muestra clasificados de forma cruzada por género y si el sujeto se autoidentificó como \"golpeado, pateado, golpeado o lastimado de otra manera por alguien en el último año\". Los sujetos que respondieron sí a esa pregunta se clasificaron como \"victimizados violentamente\". Utilice el análisis de regresión logística para encontrar los coeficientes de regresión y la estimación de la razón de probabilidades. Escriba una interpretación de sus resultados.

\
11.4.2 Consulte la investigación de Gallagher et al. (A-10) analizada en el Ejemplo 11.4.2. Otra covariable de interés fue una puntuación obtenida con el Índice de ansiedad y depresión hospitalaria. Un valor más alto de esta puntuación indica un nivel más alto de ansiedad y depresión. Utilice los siguientes datos para predecir si una mujer del estudio participó en un programa de rehabilitación cardíaca.

**11.5 SUMMARY**

\
Este capítulo se incluye para el beneficio de aquellos que desean ampliar su comprensión del análisis de regresión y su capacidad para aplicar técnicas a modelos que son más complejos que los cubiertos en los Capítulos 9 y 10. En este capítulo presentamos algunos temas adicionales del análisis de regresión. Analizamos el análisis que es apropiado cuando una o más de las variables independientes son dicotómicas. En esta discusión se presenta el concepto de codificación de variables ficticias. Un segundo tema que discutimos es cómo seleccionar las variables independientes más útiles cuando tenemos una larga lista de candidatos potenciales. La técnica que ilustramos para este propósito es el análisis de regresión por pasos. Finalmente, presentamos los conceptos y procedimientos básicos que están involucrados en el análisis de regresión logística. Cubrimos dos situaciones: el caso en el que la variable independiente es dicotómica y el caso en el que la variable independiente es continua.

Dado que los cálculos necesarios para obtener resultados útiles a partir de datos apropiados para el análisis mediante las técnicas presentadas en este capítulo son complicados y consumen mucho tiempo cuando se intentan realizar a mano, se recomienda utilizar una computadora para realizar los ejercicios.

**REVIEW QUESTIONS AND EXERCISES**

1.What is a qualitative variable?

2.¿Qué es una variable ficticia?

3\. Explique e ilustre la técnica de codificación de variables ficticias.

4.¿Por qué es importante el conocimiento de las técnicas de selección de variables para el investigador en ciencias de la salud?

5.¿Qué es la regresión por pasos?

6\. Explique el concepto básico involucrado en la regresión por pasos.

7.When is logistic regression used?

8.Write out and explain the components of the logistic regression model.

9.Define the word odds.

10.What is an odds ratio?

11.Give an example in your field in which logistic regression analysis would be appropriate when the independent variable is dichotomous.

12.Give an example in your field in which logistic regression analysis would be appropriate when the independent variable is continuous.

13.Find a published article in the health sciences field in which each of the following techniques is employed:

\(a\) Dummy variable coding

\(b\) Stepwise regression

\(c\) Logistic regression

Write a report on the article in which you identify the variables involved, the reason for the choice of the technique, and the conclusions that the authors reach on the basis of their analysis.

Redacte un informe sobre el artículo en el que identifique las variables involucradas, el motivo de la elección de la técnica y las conclusiones a las que llegan los autores con base en su análisis.

14\. In Example 10.3.1, we saw that the purpose of a study by Jansen and Keller (A-12) was to predict the capacity to direct attention (CDA) in elderly subjects. The study collected information on 71 community-dwelling older women with normal mental status. Higher CDA scores indicate better attentional functioning. In addition to the variables age and education level, the researchers performed stepwise regression with two additional variables: IADL, a measure of activities of daily living (higher values indicate greater number of daily activities), and ADS, a measure of attentional demands (higher values indicate more attentional demands). Perform stepwise regression with the data in the following table and report your final model, p values, and conclusions.

\
14. En el Ejemplo 10.3.1, vimos que el propósito de un estudio de Jansen y Keller (A-12) era predecir la capacidad de dirigir la atención (CDA) en sujetos de edad avanzada. El estudio recopiló información sobre 71 mujeres mayores que vivían en la comunidad y tenían un estado mental normal. Las puntuaciones más altas en CDA indican un mejor funcionamiento atencional. Además de las variables edad y nivel educativo, los investigadores realizaron una regresión por pasos con dos variables adicionales: IADL, una medida de las actividades de la vida diaria (los valores más altos indican un mayor número de actividades diarias) y ADS, una medida de las demandas atencionales (los valores más altos indican más demandas atencionales). Realice una regresión por pasos con los datos de la siguiente tabla e informe su modelo final, los valores p y las conclusiones.

15\. En la siguiente tabla se muestran los valores de gasto cardíaco (L/min) y consumo de oxígeno (VO2) de una muestra de adultos (A) y niños (C) que participaron en un estudio diseñado para investigar la relación entre estas variables. Las mediciones se tomaron tanto en reposo como durante el ejercicio. Considere el gasto cardíaco como la variable dependiente y utilice la codificación de variables ficticias y analice los datos mediante técnicas de regresión. Explique los resultados. Dibuje los datos originales y las ecuaciones de regresión ajustadas.

16\. Una muestra aleatoria simple de sujetos normales de entre 6 y 18 años de edad arrojó los datos sobre potasio corporal total (mEq) y agua corporal total (litros) que se muestran en la siguiente tabla. Sea el potasio total la variable dependiente y utilice la codificación de variable ficticia para cuantificar la variable cualitativa. Analice los datos utilizando técnicas de regresión. Explique los resultados. Dibuje los datos originales y las ecuaciones de regresión ajustadas.

17\. Los datos que se muestran en la siguiente tabla se recopilaron como parte de un estudio en el que los sujetos fueron bebés prematuros con bajo peso al nacer nacidos en tres hospitales diferentes. Utilice la codificación de variables ficticias y técnicas de regresión múltiple para analizar estos datos. ¿Podemos concluir que las tres poblaciones hospitalarias de muestra difieren con respecto al peso medio al nacer cuando se tiene en cuenta la edad gestacional? ¿Podemos concluir que existe interacción entre el hospital de nacimiento y la edad gestacional? Dibuje los datos originales y las ecuaciones de regresión ajustadas.

18\. Consulte el Capítulo 9, Ejercicio de revisión 18. En el estudio citado en ese ejercicio, Maria Mathias (A-13) investigó la relación entre las edades (EDAD) de los niños y la mejora en las medidas de hiperactividad, actitud y comportamiento social. En el estudio, los sujetos fueron asignados aleatoriamente a dos tratamientos diferentes. El grupo de control (TREAT = 0) recibió terapia estándar para la hiperactividad, y el grupo de tratamiento (TREAT = 1) recibió terapia estándar más terapia con mascotas. Los resultados se muestran en la siguiente tabla. Cree un diagrama de dispersión con la edad como variable independiente y ATT (cambio de actitud con números positivos que indican un cambio positivo en la actitud) como variable dependiente. Utilice símbolos diferentes para los dos grupos de tratamiento diferentes. Utilice técnicas de regresión múltiple para determinar si la edad, el tratamiento o la interacción son útiles para predecir ATT. Informe sus resultados.

\
\

For each study described in Exercises 19 through 21, answer as many of the following questions as possible:

\

\(a\) Which is the dependent variable?

\(b\) What are the independent variables?

\(c\) What are the appropriate null and alternative hypotheses?

\(d\) Which null hypotheses do you think were rejected? Why?

\(e\) Which is the more relevant objective, prediction or estimation, or are the two equally relevant? Explain your answer.

\(f\) What is the sampled population?

\(g\) What is the target population?

\(h\) Which variables are related to which other variables? Are the relationships direct or inverse?

\(i\) Write out the regression equation using appropriate numbers for parameter estimates.

( j) Give numerical values for any other statistics that you can.

\(k\) Identify each variable as to whether it is quantitative or qualitative.

\(l\) Explain the meaning of any statistics for which numerical values are given.

19\. Golfinopoulos y Arhonditsis (A-14) utilizaron un modelo de regresión múltiple en un estudio de trihalometanos (THM) en el agua potable en Atenas, Grecia. Los THM son motivo de preocupación, ya que se han relacionado con el cáncer y los problemas reproductivos. Los investigadores encontraron que el siguiente modelo de regresión era útil para predecir los THM:

THM = -.26chla + 1.57 pH + 28.74Br - 66.72Br 2

-43.63S + 1.13Sp + 2.62T \* S - .72T \* CL

\

The variables were as follows: chla = chlorophyll concentration, pH = acid/base scale, Br = bromide concentration, S = dummy variable for summer, Sp = dummy variable for spring, T = temperature, and CL = chlorine concentration. The researchers reported R = .52, p 6 .001.

\

Las variables fueron las siguientes: chla = concentración de clorofila, pH = escala ácido/base, Br = concentración de bromuro, S = variable ficticia para verano, Sp = variable ficticia para primavera, T = temperatura y CL = concentración de cloro. Los investigadores informaron un R = .52, p 6 .001.

\
\

20\. In a study by Takata et al. (A-15), investigators evaluated the relationship between chewing ability and teeth number and measures of physical fitness in a sample of subjects ages 80 or higher in Japan. One of the outcome variables that measured physical fitness was leg extensor strength. To measure the ability to chew foods, subjects were asked about their ability to chew 15 foods (peanuts, vinegared octopus, and French bread, among others). Consideration of such variables as height, body weight, gender, systolic blood pressure, serum albumin, fasting glucose concentration, back pain, smoking, alcohol consumption, marital status, regular medical treatment, and regular exercise revealed that the number of chewable foods was significant in predicting leg extensor strength 1bN 1 = .075, p = .03662. However, in the presence of the other variables, number of teeth was not a significant predictor 1bN 1 = .003, p = .93732.

\

20\. En un estudio de Takata et al. (A-15), los investigadores evaluaron la relación entre la capacidad de masticación y el número de dientes y las medidas de aptitud física en una muestra de sujetos de 80 años o más en Japón. Una de las variables de resultado que medían la aptitud física era la fuerza extensora de las piernas. Para medir la capacidad de masticar alimentos, se preguntó a los sujetos sobre su capacidad para masticar 15 alimentos (cacahuetes, pulpo avinagrado y pan francés, entre otros). La consideración de variables como la altura, el peso corporal, el sexo, la presión arterial sistólica, la albúmina sérica, la concentración de glucosa en ayunas, el dolor de espalda, el tabaquismo, el consumo de alcohol, el estado civil, el tratamiento médico regular y el ejercicio regular reveló que el número de alimentos masticables era significativo para predecir la fuerza extensora de las piernas 1bN 1 = .075, p = .03662. Sin embargo, en presencia de las otras variables, el número de dientes no fue un predictor significativo 1bN 1 = .003, p = .93732.

\
\

21\. Varela et al. (A-16) examined 515 patients who underwent lung resection for bronchogenic carcinoma. The outcome variable was the occurrence of cardiorespiratory morbidity after surgery. Any of the following postoperative events indicated morbidity: pulmonary atelectasis or pneumonia, respiratory or ventilatory insufficiency at discharge, need for mechanical ventilation at any time after extubation in the operating room, pulmonary thromboembolism, arrhythmia, myocardial ischemia or infarct, and clinical cardiac insufficiency. Performing a stepwise logistic regression, the researchers found that age 1p 6 .0012 and postoperative forced expiratory volume 1p = .0032 were statistically significant in predicting the occurrence of cardiorespiratory morbidity.

\

21\. Varela et al. (A-16) examinaron a 515 pacientes que se sometieron a resección pulmonar por carcinoma broncogénico. La variable de resultado fue la aparición de morbilidad cardiorrespiratoria después de la cirugía. Cualquiera de los siguientes eventos postoperatorios indicó morbilidad: atelectasia pulmonar o neumonía, insuficiencia respiratoria o ventilatoria al alta, necesidad de ventilación mecánica en cualquier momento después de la extubación en el quirófano, tromboembolia pulmonar, arritmia, isquemia o infarto de miocardio e insuficiencia cardíaca clínica. Al realizar una regresión logística por pasos, los investigadores encontraron que la edad 1p 6 .0012 y el volumen espiratorio forzado postoperatorio 1p = .0032 fueron estadísticamente significativos para predecir la aparición de morbilidad cardiorrespiratoria.

\
\

For each of the data sets given in Exercises 22 through 29, do as many of the following as you think appropriate:

\

Para cada uno de los conjuntos de datos dados en los ejercicios 22 a 29, realice tantas de las siguientes operaciones como considere apropiadas:

\
\

\(a\) Apply one or more of the techniques discussed in this chapter.

\(b\) Apply one or more of the techniques discussed in previous chapters.

\(c\) Construct graphs.

\(d\) Formulate relevant hypotheses, perform the appropriate tests, and find p values.

\(e\) State the statistical decisions and clinical conclusions that the results of your hypothesis tests justify.

\(f\) Describe the population(s) to which you think your inferences are applicable.

\

22\. A study by Davies et al. (A-17) was motivated by the fact that, in previous studies of contractile responses to b -adrenoceptor agonists in single myocytes from failing and nonfailing human hearts, they had observed an age-related decline in maximum response to isoproterenol, at frequencies where the maximum response to high Ca2 + in the same cell was unchanged. For the present study, the investigators computed the isoproterenol/Ca2 + ratio (ISO/CA) from measurements taken on myocytes from patients ranging in age from 7 to 70 years. Subjects were classified as older ( 750 years) and younger. The following are the (ISO/CA) values, age, and myocyte source of subjects in the study. Myocyte sources were reported as donor and biopsy.

\

22\. Un estudio de Davies et al. (A-17) fue motivado por el hecho de que, en estudios previos de respuestas contráctiles a agonistas de los receptores b-adrenérgicos en miocitos individuales de corazones humanos con insuficiencia y sin insuficiencia, habían observado una disminución relacionada con la edad en la respuesta máxima al isoproterenol, en frecuencias en las que la respuesta máxima al Ca2+ alto en la misma célula no había cambiado. Para el presente estudio, los investigadores calcularon la relación isoproterenol/Ca2+ (ISO/CA) a partir de mediciones tomadas en miocitos de pacientes con edades comprendidas entre 7 y 70 años. Los sujetos se clasificaron como mayores (750 años) y menores. A continuación se presentan los valores (ISO/CA), la edad y la fuente de miocitos de los sujetos del estudio. Las fuentes de miocitos se informaron como donante y biopsia.

\
\

23\. Hayton et al. (A-18) investigated the pharmacokinetics and bioavailability of cefetamet and cefetamet pivoxil in infants between the ages of 3.5 and 17.3 months who had received the antibiotic during and after urological surgery. Among the pharmacokinetic data collected were the following measurements of the steady-state apparent volume of distribution (V). Also shown are previously collected data on children ages 3 to 12 years (A-19) and adults (A-20). Weights (W) of subjects are also shown.

\

23\. Hayton et al. (A-18) investigaron la farmacocinética y la biodisponibilidad de cefetamet y cefetamet pivoxil en niños de entre 3,5 y 17,3 meses de edad que habían recibido el antibiótico durante y después de una cirugía urológica. Entre los datos farmacocinéticos recopilados se encontraban las siguientes mediciones del volumen de distribución aparente en estado estacionario (V). También se muestran datos recopilados previamente sobre niños de entre 3 y 12 años de edad (A-19) y adultos (A-20). También se muestran los pesos (W) de los sujetos.

\
\

24\. According to Fils-Aime et al. (A-21), epidemiologic surveys have found that alcoholism is the most common mental or substance abuse disorder among men in the United States. Fils-Aime and associates investigated the interrelationships of age at onset of excessive alcohol consumption, family history of alcoholism, psychiatric comorbidity, and cerebrospinal fluid (CSF) monoamine metabolite concentrations in abstinent, treatment-seeking alcoholics. Subjects were mostly white males classified as experiencing early (25 years or younger) or late (older than 25 years) onset of excessive alcohol consumption. Among the data collected were the following measurements on CSF tryptophan (TRYPT) and 5-hydroxyindoleacetic acid (5-HIAA) concentrations (pmol/ml).

\

24\. Según Fils-Aime et al. (A-21), las encuestas epidemiológicas han descubierto que el alcoholismo es el trastorno mental o de abuso de sustancias más común entre los hombres en los Estados Unidos. Fils-Aime y colaboradores investigaron las interrelaciones entre la edad de inicio del consumo excesivo de alcohol, los antecedentes familiares de alcoholismo, la comorbilidad psiquiátrica y las concentraciones de metabolitos de monoamina en el líquido cefalorraquídeo (LCR) en alcohólicos abstinentes que buscaban tratamiento. Los sujetos eran en su mayoría varones blancos clasificados como que experimentaban un inicio temprano (25 años o menos) o tardío (más de 25 años) de consumo excesivo de alcohol. Entre los datos recopilados se encontraban las siguientes mediciones de las concentraciones de triptófano (TRYPT) y ácido 5-hidroxiindolacético (5-HIAA) en el LCR (pmol/ml).

\
\

25\. The objective of a study by Abrahamsson et al. (A-22) was to investigate the anti-thrombotic effects of an inhibitor of the plasminogen activator inhibitor-1 (PAI-1) in rats given endotoxin. Experimental subjects were male Sprague--Dawley rats weighing between 300 and 400 grams. Among the data collected were the following measurements on PAI-1 activity and the lung 125I-concentration in anesthetized rats given three drugs:

\

25\. El objetivo de un estudio realizado por Abrahamsson et al. (A-22) fue investigar los efectos antitrombóticos de un inhibidor del inhibidor del activador del plasminógeno-1 (PAI-1) en ratas a las que se les administró endotoxina. Los sujetos experimentales fueron ratas Sprague-Dawley macho que pesaban entre 300 y 400 gramos. Entre los datos recopilados se encontraban las siguientes mediciones de la actividad del PAI-1 y la concentración pulmonar de 125I en ratas anestesiadas a las que se les administraron tres fármacos:

\
\

26\. Pearse and Sylvester (A-23) conducted a study to determine the separate contributions of ischemia and extracorporeal perfusion to vascular injury occurring in isolated sheep lungs and to determine the oxygen dependence of this injury. Lungs were subjected to ischemia alone, extracorporeal perfusion alone, and both ischemia and extracorporeal perfusion. Among the data collected were the following observations on change in pulmonary arterial pressure (mm Hg) and pulmonary vascular permeability assessed by estimation of the reflection coefficient for albumin in perfused lungs with and without preceding ischemia:

\

26\. Pearse y Sylvester (A-23) realizaron un estudio para determinar las contribuciones independientes de la isquemia y la perfusión extracorpórea a la lesión vascular que se produce en pulmones aislados de ovejas y para determinar la dependencia del oxígeno de esta lesión. Los pulmones se sometieron a isquemia únicamente, a perfusión extracorpórea únicamente y a ambas, isquemia y perfusión extracorpórea. Entre los datos recopilados se encontraban las siguientes observaciones sobre el cambio en la presión arterial pulmonar (mmHg) y la permeabilidad vascular pulmonar evaluada mediante la estimación del coeficiente de reflexión de la albúmina en pulmones perfundidos con y sin isquemia previa:

\
\

27\. The purpose of a study by Balzamo et al. (A-24) was to investigate, in anesthetized rabbits, the effects of mechanical ventilation on the concentration of substance P (SP) measured by radioimmunoassay in nerves and muscles associated with ventilation and participating in the sensory innervation of the respiratory apparatus and heart. SP is a neurotransmitter located in primary sensory neurons in the central and autonomic nervous systems. Among the data collected were the following measures of SP concentration in cervical vagus nerves (X) and corresponding nodose ganglia (NG), right and left sides:

\

27\. El objetivo de un estudio realizado por Balzamo et al. (A-24) fue investigar, en conejos anestesiados, los efectos de la ventilación mecánica sobre la concentración de sustancia P (SP) medida por radioinmunoensayo en nervios y músculos asociados con la ventilación y que participan en la inervación sensorial del aparato respiratorio y el corazón. La SP es un neurotransmisor ubicado en neuronas sensoriales primarias en los sistemas nerviosos central y autónomo. Entre los datos recopilados se encuentran las siguientes mediciones de concentración de SP en los nervios vagos cervicales (X) y los ganglios nodosos correspondientes (NG), lados derecho e izquierdo:

\
\

28\. Scheeringa and Zeanah (A-25) examined the presence of posttraumatic stress disorder (PTSD), the severity of posttraumatic symptomatology, and the pattern of expression of symptom clusters in relation to six independent variables that may be salient to the development of a posttraumatic disorder in children under 48 months of age. The following data were collected during the course of the study.

\

28\. Scheeringa y Zeanah (A-25) examinaron la presencia de trastorno de estrés postraumático (TEPT), la gravedad de la sintomatología postraumática y el patrón de expresión de los grupos de síntomas en relación con seis variables independientes que pueden ser relevantes para el desarrollo de un trastorno postraumático en niños menores de 48 meses de edad. Los siguientes datos se recopilaron durante el curso del estudio.

\
\

Wit./exper.

0 = subject witnessed but did not directly experience trauma

1 = subject directly experienced the trauma

Threat to caregiver

0 = caregiver was not threatened in the trauma

1 = caregiver was threatened in the trauma

Reexp " Reexperiencing cluster symptom count

Numb " Numbing of responsiveness/avoidance cluster symptom count

Arous " Hyperarousal cluster symptom count

FrAgg " New fears/aggression cluster symptom count

\
\

29\. One of the objectives of a study by Mulloy and McNicholas (A-26) was to compare ventilation and gas exchange during sleep and exercise in chronic obstructive pulmonary disease (COPD). The investigators wished also to determine whether exercise studies could aid in the prediction of nocturnal desaturation in COPD. Subjects (13 male, 6 female) were ambulatory patients attending an outpatient respiratory clinic. The mean age of the patients, all of whom had severe, stable COPD, was 64.8 years with a standard deviation of 5.2. Among the data collected were measurements on the following variables:

\

29\. Uno de los objetivos de un estudio realizado por Mulloy y McNicholas (A-26) fue comparar la ventilación y el intercambio de gases durante el sueño y el ejercicio en la enfermedad pulmonar obstructiva crónica (EPOC). Los investigadores también deseaban determinar si los estudios de ejercicio podían ayudar a predecir la desaturación nocturna en la EPOC. Los sujetos (13 hombres, 6 mujeres) eran pacientes ambulatorios que asistían a una clínica respiratoria ambulatoria. La edad media de los pacientes, todos ellos con EPOC grave y estable, era de 64,8 años con una desviación estándar de 5,2. Entre los datos recopilados se encontraban mediciones de las siguientes variables:

\

Exercises for Use with the Large Data Sets Available on the Following Website:

www.wiley.com/college/daniel

\

1\. The goal of a study by Gyurcsik et al. (A-27) was to examine the usefulness of aquatic exercise-related goals, task self-efficacy, and scheduling self-efficacy for predicting aquatic exercise attendance by individuals with arthritis. The researchers collected data on 142 subjects participating in Arthritis Foundation Aquatics Programs. The outcome variable was the percentage of sessions attended over an 8-week period (ATTEND). The following predictor variables are all centered values. Thus, for each participant, the mean for all participants is subtracted from the individual score. The variables are:

\

1\. El objetivo de un estudio realizado por Gyurcsik et al. (A-27) fue examinar la utilidad de las metas relacionadas con el ejercicio acuático, la autoeficacia en la tarea y la autoeficacia en la programación para predecir la asistencia al ejercicio acuático por parte de personas con artritis. Los investigadores recopilaron datos sobre 142 sujetos que participaban en los programas acuáticos de la Arthritis Foundation. La variable de resultado fue el porcentaje de sesiones a las que se asistió durante un período de 8 semanas (ATTEND). Las siguientes variables predictoras son todas valores centrados. Por lo tanto, para cada participante, la media de todos los participantes se resta de la puntuación individual. Las variables son:

\
\

GOALDIFF---higher values indicate setting goals of higher participation.

GOALSPEC---higher values indicate higher specificity of goals related to aquatic exercise.

INTER---interaction of GOALDIFF and GOALSPEC.

TSE---higher values indicate participants\' confidence in their abilities to attend aquatic

classes.

SSE---higher values indicate participants\' confidence in their abilities to perform eight tasks

related to scheduling exercise into their daily routine for 8 weeks.

MONTHS---months of participation in aquatic exercise prior to start of study.

\

With the data set AQUATICS, perform a multiple regression to predict ATTEND with each of the above variables. What is the multiple correlation coefficient? What variables are significant in predicting ATTEND? What are your conclusions?

\

Con el conjunto de datos AQUATICS, realice una regresión múltiple para predecir ATTEND con cada una de las variables anteriores. ¿Cuál es el coeficiente de correlación múltiple? ¿Qué variables son significativas para predecir ATTEND? ¿Cuáles son sus conclusiones?

\
\

2\. Rodehorst (A-28) conducted a prospective study of 212 rural elementary school teachers. The main outcome variable was the teachers\' intent to manage children demonstrating symptoms of asthma in their classrooms. This variable was measured with a single-item question that used a seven-point Likert scale (INTENT, with possible responses of 1 = extremely probable to 7 = extremely improbable). Rodehorst used the following variables as independent variables to predict INTENT:

\

2\. Rodehorst (A-28) realizó un estudio prospectivo de 212 maestros de escuelas primarias rurales. La variable de resultado principal fue la intención de los maestros de manejar a los niños que presentaban síntomas de asma en sus aulas. Esta variable se midió con una pregunta de un solo ítem que utilizó una escala Likert de siete puntos (INTENT, con posibles respuestas de 1 = extremadamente probable a 7 = extremadamente improbable). Rodehorst utilizó las siguientes variables como variables independientes para predecir la INTENCIÓN:

\
\

SS = Social Support. Scores range from 7 to 49, with higher scores indicating higher perceived social support for managing children with asthma in a school setting.

ATT = Attitude. Scores range from 15 to 90, with higher scores indicating more favorable attitudes toward asthma.

KNOW = Knowledge. Scores range from 0 to 24, with higher scores indicating higher general knowledge about asthma.

CHILD = Number of children with asthma the teacher has had in his or her class during his or her entire teaching career.

SE = Self-efficacy. Scores range from 12 to 60, with higher scores indicating higher self-efficacy for managing children with asthma in the school setting.

YRS = Years of teaching experience.

With the data TEACHERS, use stepwise regression analysis to select the most useful variables to include in a model for predicting INTENT.

\

3\. Refer to the weight loss data on 588 cancer patients and 600 healthy controls (WGTLOSS). Weight loss among cancer patients is a well-known phenomenon. Of interest to clinicians is the role played in the process by metabolic abnormalities. One investigation into the relationships among these variables yielded data on whole-body protein turnover (Y ) and percentage of ideal body weight for height (X ). Subjects were lung cancer patients and healthy controls of the same age. Select a simple random sample of size 15 from each group and do the following:

\

3\. Consulte los datos de pérdida de peso de 588 pacientes con cáncer y 600 controles sanos (WGTLOSS). La pérdida de peso entre los pacientes con cáncer es un fenómeno bien conocido. A los médicos les interesa el papel que desempeñan las anomalías metabólicas en el proceso. Una investigación sobre las relaciones entre estas variables arrojó datos sobre el recambio proteico de todo el cuerpo (Y ) y el porcentaje del peso corporal ideal para la altura (X ). Los sujetos eran pacientes con cáncer de pulmón y controles sanos de la misma edad. Seleccione una muestra aleatoria simple de tamaño 15 de cada grupo y haga lo siguiente:

\
\

\(a\) Draw a scatter diagram of the sample data using different symbols for each of the two groups.

\(b\) Use dummy variable coding to analyze these data.

\(c\) Plot the two regression lines on the scatter diagram. May one conclude that the two sampled

populations differ with respect to mean protein turnover when percentage of ideal weight is taken

into account?

\

May one conclude that there is interaction between health status and percentage of ideal body weight? Prepare a verbal interpretation of the results of your analysis and compare your results with those of your classmates.

\
\
\
